# Generated by Django 2.0.7 on 2019-07-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
                ('units', models.IntegerField()),
                ('unitprice', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tuprice', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
